apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-otrudsij
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-otrudsij:fa55f0f9e89936603a3f1ac222457f2dcfa4dae1@sha256:fc195185b66f53770497754dc5d9b310a375bb762d4129eb1acb86fd9fdca3fa
        name: container-image  
